version: '3'
services:
  unleash:
    image: 'unleashorg/unleash-server:latest'
    container_name: 'unleash'
    environment:
      - DATABASE_URL=postgres://unleash_user:password@db:5432/unleash
      - DATABASE_SSL=false
    ports:
      - "4242:4242"
    depends_on:
      - db
  db:
    image: 'postgres:latest'
    container_name: 'db'
    environment:
      - POSTGRES_USER=unleash_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=unleash
    volumes:
      - db_data:/var/lib/postgresql/data
  vault:
    image: 'hashicorp/vault'
    container_name: 'vault'
    ports:
      - "8200:8200"
    environment: 
      - VAULT_DEV_ROOT_TOKEN_ID=p1nk@ndBlueH0tel
    volumes:
      - vault_data:/vault/file
  proxy:
    image: 'unleashorg/unleash-proxy:latest'
    container_name: 'unleash-proxy'
    environment:
      - UNLEASH_PROXY_SECRETS=some-secret
      - UNLEASH_URL=http://unleash:4242/api/
      - UNLEASH_API_TOKEN=*:development.fd17bed97974bcece72913b6cd2406fb10070668453efceff1c68c43
    ports:
      - "3000:3000"
    depends_on:
      - unleash
volumes:
  db_data:
  vault_data: