version: '3'
services:
  mssql:
    image: 'mcr.microsoft.com/mssql/server:2022-latest'
    container_name: 'mssql'
    build: .
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pwd12345!
    ports:
      - "1433:1433"